apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: robust-tjanst
build:
  artifacts:
  - image: iteam1337/robust-web
    docker:
      dockerfile: packages/web/Dockerfile
  - image: iteam1337/robust-admin
    docker:
      dockerfile: packages/admin/Dockerfile
deploy:
  helm:
    releases:
      - name: redis
        remoteChart: redis
        repo: https://charts.bitnami.com/bitnami

      # - name: postgresql
      #   remoteChart: postgresql
      #   repo: https://charts.bitnami.com/bitnami
        # https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart
        # setValues:
        #   replication.enabled: true
      
  kubectl:
    defaultNamespace: dev
    manifests:
    - k8s/admin.yaml
    - k8s/web.yaml
