# Deploy dependencies first
apiVersion: skaffold/v2beta13
kind: Config
deploy:
  kubectl:
    manifests:
    - k8s/test-runner-account.yaml
    - k8s/registry.yaml
    - k8s/certManager.yaml
    - k8s/nginx-config-map.yaml
  helm:
    releases:
      - name: redis
        remoteChart: redis
        repo: https://charts.bitnami.com/bitnami
        namespace: prod
        setValues:
          replica.replicaCount: 3
      - name: postgresql
        setValues:
          volumePermissions.enabled: true
        remoteChart: postgresql-ha
        version: 9.4.10
        repo: https://charts.bitnami.com/bitnami
        namespace: prod
---
# Deploy services after
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: robust-tjanst
build:
  artifacts:
  - image: netnodse/robust-web
    docker:
      dockerfile: Dockerfile.web
  - image: netnodse/robust-admin
    docker:
      dockerfile: Dockerfile.admin
  - image: netnodse/robust-test-runner
    docker:
      dockerfile: Dockerfile.tests
deploy:
  kubectl:
    defaultNamespace: prod
    manifests:
    - k8s/admin.yaml
    - k8s/web.yaml
    - k8s/tests.yaml
