name: Build and push tests
on:
  push:
    branches: [main]
    paths: # run this on changes in tests that are not messages or readme
      - 'packages/tests/tests/**'
      - '!packages/tests/tests/**/messages.js'
      - '!packages/tests/tests/README.md'

jobs:
  build-and-push:
    name: Push test images to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        # Checks-out your repository under $GITHUB_WORKSPACE
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     

      - name: Install Skaffold
        run: | 
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/

      - name: Build and push images
        run: |
          cd $GITHUB_WORKSPACE/packages/tests && skaffold build
